version: '3.4'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "8000:80"
      - "80:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=host
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - "3306:3306"
      - "3307:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"